# Application configuration, split by sensitivity:
#   - Secrets Manager: sensitive values (API keys, passwords)
#   - SSM Parameter Store: non-sensitive settings
# ECS injects both into the container at start-up as environment variables.
# They never appear in the image, the Git repository or the GitHub workflow.

resource "random_password" "api_secret" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "api_secret" {
  name        = "${local.name}/backend/api-secret"
  description = "Example application secret for the ${var.environment} backend"

  # Lab setting: delete immediately on destroy so the name can be reused.
  # Production should keep the default 30-day recovery window.
  recovery_window_in_days = 0
}

# Note: a value generated by Terraform is stored in Terraform state, which is
# why the state bucket is private, encrypted and versioned. Alternatives:
# set the value out of band (aws secretsmanager put-secret-value) or use
# Secrets Manager rotation.
resource "aws_secretsmanager_secret_version" "api_secret" {
  secret_id     = aws_secretsmanager_secret.api_secret.id
  secret_string = random_password.api_secret.result
}

resource "aws_ssm_parameter" "app_message" {
  name  = "/${var.project}/${var.environment}/backend/APP_MESSAGE"
  type  = "String"
  value = var.app_message
}
